# Auto-generated by the Retrace CLI release pipeline (retrace/.github/workflows/cli.yml).
# Do not edit by hand — changes are overwritten on the next CLI release.
cask "retrace-cli" do
  version "1.6.8"

  on_macos do
    on_arm do
      sha256 "e6318411b95348e4ab7fc0ae3689917682f588bc94c18f99062b6ca97f5c602b"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-aarch64"
      binary "retrace-darwin-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "35e4c5dc8c7e998031a780cf6f99fdcc968de208132690044b1b606d7c08ac91"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-x86_64"
      binary "retrace-darwin-x86_64", target: "retrace"
    end
  end

  on_linux do
    on_arm do
      sha256 "deca7645bd23b49306068a49c3f7f3fb2cdbb24b47ecf365fec86c9f3c85b728"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-aarch64"
      binary "retrace-linux-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "35c58f9c959a501662a94df75693e793b9fecac991e5590f54b987cbba2fd98e"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-x86_64"
      binary "retrace-linux-x86_64", target: "retrace"
    end
  end

  name "Retrace CLI"
  desc "Record, replay, fork, and manage AI agent traces"
  homepage "https://cli.retraceai.tech/"

  livecheck do
    url "https://cdn.retraceai.tech/cli/latest/VERSION"
    regex(/(\d+(?:\.\d+)+)/i)
  end

  # The binary isn't yet Developer ID-signed/notarized, so Homebrew's download quarantine would make
  # Gatekeeper block it on first run. Strip the quarantine attribute on install so `brew install` is
  # seamless. (Durable fix: codesign + notarize in CI — then this can be removed.)
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path], must_succeed: false
  end

  caveats <<~EOS
    Retrace has been installed as `retrace`.

      retrace auth login
      retrace --help

    Update with: brew upgrade retrace-cli
  EOS
end
