# Auto-generated by the Retrace CLI release pipeline (retrace/.github/workflows/cli.yml).
# Do not edit by hand — changes are overwritten on the next CLI release.
cask "retrace-cli" do
  version "1.6.17"

  on_macos do
    on_arm do
      sha256 "9d0386d159b39a9fd5c4cea4607558da327790f1721a1735576100ec95031314"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-aarch64"
      binary "retrace-darwin-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "1c7fa48ced6792c73d571ad2441b366f691891919c5cdd983209b21ef5f04e2a"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-x86_64"
      binary "retrace-darwin-x86_64", target: "retrace"
    end
  end

  on_linux do
    on_arm do
      sha256 "e70d0a95c12bb89e3760a59f28a8c5045aa9cf0e902defe54f2e014d59cf7aae"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-aarch64"
      binary "retrace-linux-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "57379bfea376ee70bd8a4e3bcb2c787c104f92e36bb67bbe93a3510a88e0db36"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-x86_64"
      binary "retrace-linux-x86_64", target: "retrace"
    end
  end

  name "Retrace CLI"
  desc "Record, replay, fork, and manage AI agent traces"
  homepage "https://cli.retraceai.tech/"

  livecheck do
    url "https://cdn.retraceai.tech/cli/latest/VERSION"
    regex(/(\d+(?:\.\d+)+)/i)
  end

  # The binary isn't yet Developer ID-signed/notarized, so Homebrew's download quarantine would make
  # Gatekeeper block it on first run. Strip the quarantine attribute on install so `brew install` is
  # seamless. (Durable fix: codesign + notarize in CI — then this can be removed.) macOS only: xattr
  # and Gatekeeper quarantine don't exist on Linux.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path], must_succeed: false
    end
  end

  caveats <<~EOS
    Retrace has been installed as `retrace`.

      retrace auth login
      retrace --help

    Update with: brew upgrade --cask retrace-cli

    Linux: the binaries are statically linked (no glibc requirement).
  EOS
end
