# Auto-generated by the Retrace CLI release pipeline (retrace/.github/workflows/cli.yml).
# Do not edit by hand — changes are overwritten on the next CLI release.
cask "retrace" do
  version "1.6.7"

  on_macos do
    on_arm do
      sha256 "8578708d5945a97a38687e020d6aa9dbf5b94593ee2868be4a59a6ff7b9db1fd"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-aarch64"
      binary "retrace-darwin-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "bc6f45573f6ed9619c4df2df14bba71c075caa31918527d1ddcd11d3437f3ff2"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-x86_64"
      binary "retrace-darwin-x86_64", target: "retrace"
    end
  end

  on_linux do
    on_arm do
      sha256 "f073f0e879fa0c87d28aeeeca43f65c8816ccf0d65f0a11095dbf4cab0d8cdeb"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-aarch64"
      binary "retrace-linux-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "e762f1fb94aa6f71b93150c4c91b5c46d13f7f66cd3b5cf9e8eb1c9609a1b98e"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-x86_64"
      binary "retrace-linux-x86_64", target: "retrace"
    end
  end

  name "Retrace CLI"
  desc "Record, replay, fork, and manage AI agent traces"
  homepage "https://cli.retraceai.tech/"

  livecheck do
    url "https://cdn.retraceai.tech/cli/latest/VERSION"
    regex(/(\d+(?:\.\d+)+)/i)
  end

  caveats <<~EOS
    Retrace has been installed as `retrace`.

      retrace auth login
      retrace --help

    Update with: brew upgrade --cask retrace
  EOS
end
