# Auto-generated by the Retrace CLI release pipeline (retrace/.github/workflows/cli.yml).
# Do not edit by hand — changes are overwritten on the next CLI release.
cask "retrace-cli" do
  version "1.6.7"

  on_macos do
    on_arm do
      sha256 "41502b4537e49559d94139468d93e2aebe6afa773412b2d77b3835299b79f470"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-aarch64"
      binary "retrace-darwin-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "74305d7c4029a416af9a70e7fd9661fa3a97cd46c0aad25817f7e9ed6b04d969"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-darwin-x86_64"
      binary "retrace-darwin-x86_64", target: "retrace"
    end
  end

  on_linux do
    on_arm do
      sha256 "82a74587c7bbd9fcadb545200ca6a5ea5c4f71bf01dfc1b1d59b06d07f5739a1"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-aarch64"
      binary "retrace-linux-aarch64", target: "retrace"
    end
    on_intel do
      sha256 "34e33f1253eb14c36484bb704ccc02eafc40ea982cba3c1a78451ab7a13c3527"
      url "https://cdn.retraceai.tech/cli/#{version}/retrace-linux-x86_64"
      binary "retrace-linux-x86_64", target: "retrace"
    end
  end

  name "Retrace CLI"
  desc "Record, replay, fork, and manage AI agent traces"
  homepage "https://cli.retraceai.tech/"

  livecheck do
    url "https://cdn.retraceai.tech/cli/latest/VERSION"
    regex(/(\d+(?:\.\d+)+)/i)
  end

  # The binary isn't yet Developer ID-signed/notarized, so Homebrew's download quarantine would make
  # Gatekeeper block it on first run. Strip the quarantine attribute on install so `brew install` is
  # seamless. (Durable fix: codesign + notarize in CI — then this can be removed.)
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path], must_succeed: false
  end

  caveats <<~EOS
    Retrace has been installed as `retrace`.

      retrace auth login
      retrace --help

    Update with: brew upgrade retrace-cli
  EOS
end
